import { UserType } from "../types/user";

export const mockUsers: UserType[] = [
  {
    id: 'user1',
    name: 'Ivan Kovalenko',
    email: 'ivan.kovalenko@example.com',
    status: 'Online',
    lastLogin: '2025-07-04 17:30',
  },
  {
    id: 'user2',
    name: 'Olena Petrenko',
    email: 'olena.petrenko@example.com',
    status: 'Online',
    lastLogin: '2025-07-04 17:55',
  },
  {
    id: 'user3',
    name: 'Serhii Bondar',
    email: 'serhii.bondar@example.com',
    status: 'Offline',
    lastLogin: '2025-07-03 22:10',
  },
  {
    id: 'user4',
    name: 'Maryna Tkachenko',
    email: 'maryna.tkachenko@example.com',
    status: 'Online',
    lastLogin: '2025-07-04 17:40',
  },
  {
    id: 'user5',
    name: 'Dmytro Shevchenko',
    email: 'dmytro.shevchenko@example.com',
    status: 'Offline',
    lastLogin: '2025-07-02 09:00',
  },
  {
    id: 'user6',
    name: 'Nataliia Osadcha',
    email: 'nataliia.osadcha@example.com',
    status: 'Online',
    lastLogin: '2025-07-04 17:20',
  },
  {
    id: 'user7',
    name: 'Andrii Melnyk',
    email: 'andrii.melnyk@example.com',
    status: 'Offline',
    lastLogin: '2025-07-01 14:05',
  },
  {
    id: 'user8',
    name: 'Yuliia Polishchuk',
    email: 'yulia.polishchuk@example.com',
    status: 'Online',
    lastLogin: '2025-07-04 16:50',
  },
  {
    id: 'user9',
    name: 'Oleh Savchenko',
    email: 'oleh.savchenko@example.com',
    status: 'Offline',
    lastLogin: '2025-06-30 11:30',
  },
  {
    id: 'user10',
    name: 'Khrystyna Lysenko',
    email: 'khrystyna.lysenko@example.com',
    status: 'Online',
    lastLogin: '2025-07-04 17:05',
  },
  {
    id: 'user11',
    name: 'Roman Kravchenko',
    email: 'roman.kravchenko@example.com',
    status: 'Offline',
    lastLogin: '2025-07-04 08:15',
  },
  {
    id: 'user12',
    name: 'Sofiia Moroz',
    email: 'sofiia.moroz@example.com',
    status: 'Online',
    lastLogin: '2025-07-04 16:40',
  },
  {
    id: 'user13',
    name: 'Vitalii Semeniuk',
    email: 'vitalii.semeniuk@example.com',
    status: 'Offline',
    lastLogin: '2025-06-25 19:20',
  },
  {
    id: 'user14',
    name: 'Daria Kovalchuk',
    email: 'daria.kovalchuk@example.com',
    status: 'Online',
    lastLogin: '2025-07-04 17:10',
  },
  {
    id: 'user15',
    name: 'Artem Zakharchenko',
    email: 'artem.zakharchenko@example.com',
    status: 'Offline',
    lastLogin: '2025-07-03 07:00',
  },
];